name: flutter_social_demo
description: A simple social network demo app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  loading_animation_widget: ^1.2.0+2
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  flutter_svg: ^1.1.1+1
  pull_to_refresh: ^2.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.9.3
  build_runner: ^2.2.0

flutter_icons:
  image_path: 'assets/app_icons/computer_network.png'
#  image_path_ios: 'assets/app_icons/computer_network.png' #this line is used to specify a separate file for ios
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/app_icons/
    - assets/icons/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700